'use client'
// import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Navbar from "@/components/Navbar";
import { useEffect, useRef } from 'react';
// import LocomotiveScroll from 'locomotive-scroll';

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };



export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  const containerRef = useRef(null);

  // useEffect(() => {
  //   if (typeof window !== 'undefined') {
  //     const scroll = new LocomotiveScroll({
  //       el: containerRef.current,
  //       // smooth: true,
  //     });

  //     return () => scroll.destroy();
  //   }
  // }, []);

  return (
    <html lang="en" className="dark">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        data-scroll-container ref={containerRef}
      >
        <div className="relative w-full flex items-center justify-center border-1 border-white" >
          <Navbar />
        </div>
        {children}
      </body>
    </html>
  );
}
